SCR_CampaignFaction : "{DB9CB8F07DBB0EFD}Configs/Factions/PEAKOM.conf" {
 m_aStartingVehicles {
  "{295F3684EB4ABD30}Prefabs/Vehicles/Wheeled/M923A1/PEAKOM_M923A1_transport_MERDC_filled.et"
  "{295F3684EB4ABD30}Prefabs/Vehicles/Wheeled/M923A1/PEAKOM_M923A1_transport_MERDC_filled.et"
  "{A6A358856AFC604B}Prefabs/Vehicles/Wheeled/M923A1/PEAKOM_M923A1_engineer_MERDC_filled.et"
  "{A64C2E610A49F4FF}Prefabs/Vehicles/Wheeled/Conflict_Variants/PEAKOM_M1025_armed_M2HB_MERDC_Conflict.et"
  "{A64C2E610A49F4FF}Prefabs/Vehicles/Wheeled/Conflict_Variants/PEAKOM_M1025_armed_M2HB_MERDC_Conflict.et"
 }
 m_MobileHQPrefab "{9D84AB2617AE6B16}Prefabs/MP/Campaign/Assets/PEAKOM_CampaignMobileAssemblyWest.et"
 m_RadioPrefab "{6508B531B9A44E22}Prefabs/Items/Equipment/Radios/PEAKOM_Radio_ANPRC77.et"
 m_BaseBuildingHQ "{E8F7A4D748A822BF}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_Headquarters_S_Conflict_PEAKOM_01.et"
 m_sBaseBuildingSourceBase "{1AB5F193C1EBE0AD}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_SourceBase_S_PEAKOM_01.et"
}