SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{692A884C3D54F91F}" {
   m_sEntityPrefab "{624B75BFC4D80CFB}Prefabs/Characters/Factions/PEAKOM/Character_PEAKOM_Rifleman.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{692A884C3D54F910}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{692A884C3D54F911}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{692A884C3D5632D5}" {
   m_sEntityPrefab "{7C02DB9B670987E6}Prefabs/Characters/Factions/PEAKOM/Character_PEAKOM_AR.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{692A884C3D5632E3}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{692A884C3D5632E2}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{692A884C3D5240D4}" {
   m_sIdentifier "Campaign"
   m_aEntities {
    SCR_EntityCatalogEntry "{692A884C3D52AA73}" {
     m_sEntityPrefab "{2C566BCACE0EAB84}Prefabs/Characters/Core/Character_PEAKOM_Player.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{692A884C3D52AA75}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{692A884C3D52AA74}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
    SCR_EntityCatalogEntry "{692A884C3D53EE2E}" {
     m_sEntityPrefab "{E5A77FA5D0F96341}Prefabs/Characters/Factions/PEAKOM/Character_PEAKOM_Rifleman_Player.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{692A884C3D53EE2D}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{692A884C3D53EE2C}" {
       m_fSpawnSupplyCost 66
       m_eRequiredRank RENEGADE
      }
     }
    }
    SCR_EntityCatalogEntry "{692A884C3D531CC9}" {
     m_sEntityPrefab "{2BFDDB6BCF6A6283}Prefabs/Characters/Factions/PEAKOM/Character_PEAKOM_AR_Player.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{692A884C3D531CC8}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{692A884C3D531CCB}" {
       m_fSpawnSupplyCost 99
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{692A884C3D4E91E2}" {
   m_sIdentifier "Variants"
   m_aEntities {
    SCR_EntityCatalogEntry "{692A884C3D4E91E5}" {
     m_sEntityPrefab "{EA158B6EB6A24B4B}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Rifleman_Variant_1.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{692A884C3D4E9A18}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
    SCR_EntityCatalogEntry "{692A884C3D4E9A19}" {
     m_sEntityPrefab "{07B92B5E1A781635}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Campaign_US_Player_Variant_1.et"
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{692A884C3D4E9A1A}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
   }
  }
 }
}