SCR_EntityCatalogMultiList {
 m_eEntityCatalogType NONE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6894DC36CA270C4F}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6894DC36CA270C5F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA270C55}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA270C50}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA270C7B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA27BD9D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA279021}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA2466CD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA240524}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA240519}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA24AC24}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA2562B9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA227BA3}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA227BA9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA24AC3D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA22A26B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA22A26E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA22A26C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA229729}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA22970E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA234F73}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA23EA9A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA2385B4}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA2385B9}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6894DC36CA2385BA}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6894DC36CA2385BD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA200C0A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA200C15}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6894DC36CA200C10}" {
     m_bEnabled 0
    }
   }
  }
 }
}