SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{656636120A3ECEFF}" {
   m_Info SCR_UIInfo "{656636120415FC65}" {
    Name "TNI Angkatan Darat"
    Description "Tentara Nasional Indonesia"
   }
   m_Order 0
   m_LabelType FACTION_PEAKOM
  }
 }
}